DROP TABLE IF EXISTS m_member;

CREATE TABLE IF NOT EXISTS m_member
(
	account_id INT NOT NULL PRIMARY KEY auto_increment,
	name VARCHAR(50) NOT NULL,
	furigana VARCHAR(50) NOT NULL,
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	delete_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS t_member;

CREATE TABLE IF NOT EXISTS t_member
(
	account_id INT NOT NULL PRIMARY KEY auto_increment,
	team_position VARCHAR(50) NOT NULL,
	birth_place VARCHAR(50),
	hobby VARCHAR(200),
	status_message VARCHAR(513),
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS diary;

CREATE TABLE IF NOT EXISTS diary
(
	article_id INT PRIMARY KEY auto_increment,
	title VARCHAR(500) NOT NULL,
	text VARCHAR(2500) NOT NULL,
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);